import "server-only"; import type {ContentStatus,SiteLinkKind} from "@/generated/prisma/client"; import {getPrisma} from "@/lib/prisma"; import type {FaqInput,LinkInput,ManagedInput,ManagedKind,SettingInput} from "./site-settings.schema";
const publish=(status:string)=>status==="PUBLISHED"?new Date():null;
export function listManagedContent(){const db=getPrisma();return Promise.all([db.siteLink.findMany({where:{deletedAt:null},orderBy:[{kind:"asc"},{displayOrder:"asc"}]}),db.faq.findMany({where:{deletedAt:null},orderBy:{displayOrder:"asc"}})]);}
export function getManagedItem(kind:ManagedKind,id:string){const db=getPrisma();return kind==="link"?db.siteLink.findFirst({where:{id,deletedAt:null}}):db.faq.findFirst({where:{id,deletedAt:null}});}
export function createManagedItem(kind:ManagedKind,userId:string,input:ManagedInput){const db=getPrisma();const status=input.status as ContentStatus;return kind==="link"?db.siteLink.create({data:{...(input as LinkInput),kind:(input as LinkInput).kind as SiteLinkKind,userId,status,publishedAt:publish(status)}}):db.faq.create({data:{...(input as FaqInput),userId,status,publishedAt:publish(status)}});}
export function updateManagedItem(kind:ManagedKind,id:string,input:ManagedInput){const db=getPrisma();const status=input.status as ContentStatus;const common={status,publishedAt:publish(status),version:{increment:1}};return kind==="link"?db.siteLink.update({where:{id},data:{...(input as LinkInput),kind:(input as LinkInput).kind as SiteLinkKind,...common}}):db.faq.update({where:{id},data:{...(input as FaqInput),...common}});}
export function softDeleteManagedItem(kind:ManagedKind,id:string){const db=getPrisma();const data={deletedAt:new Date(),version:{increment:1}};return kind==="link"?db.siteLink.update({where:{id},data}):db.faq.update({where:{id},data});}
export const getSiteSetting=(userId:string)=>getPrisma().siteSetting.findUnique({where:{userId}});
export function saveSiteSetting(userId:string,input:SettingInput){const status=input.status as ContentStatus;const data={...input,status,publishedAt:publish(status),deletedAt:null};return getPrisma().siteSetting.upsert({where:{userId},create:{...data,userId},update:{...data,version:{increment:1}}});}
export function countManagedContent(){const db=getPrisma();return Promise.all([db.siteLink.count({where:{deletedAt:null}}),db.faq.count({where:{deletedAt:null}})]);}
