export const MANAGED_KINDS = ["link", "faq"] as const; export const LINK_KINDS = ["NAVIGATION", "FOOTER", "SOCIAL"] as const; export const STATUSES = ["DRAFT", "PUBLISHED", "HIDDEN"] as const;
export type ManagedKind = (typeof MANAGED_KINDS)[number]; type Common = { status: (typeof STATUSES)[number]; displayOrder: number };
export type LinkInput = Common & { kind: (typeof LINK_KINDS)[number]; label: string; url: string; openNewTab: boolean };
export type FaqInput = Common & { question: string; answer: string }; export type ManagedInput = LinkInput | FaqInput;
export type SettingInput = { siteName: string; tagline: string; footerText: string; privacyNote: string; seoTitle: string; seoDescription: string; canonicalUrl: string | null; seoImagePath: string | null; status: (typeof STATUSES)[number] };
const value=(form:FormData,key:string)=>String(form.get(key)??"").trim();
function url(input:string, allowInternal:boolean, errors:string[], label:string){if(!input)return null;try{const parsed=new URL(input,"https://coffeehub.invalid");if(parsed.origin==="https://coffeehub.invalid"){if(!allowInternal||!input.startsWith("/"))throw new Error();return input;}if(!["http:","https:"].includes(parsed.protocol))throw new Error();return parsed.toString();}catch{errors.push(`${label} không hợp lệ.`);return null;}}
function common(form:FormData,errors:string[]){const status=STATUSES.find(item=>item===value(form,"status"));const displayOrder=Number(value(form,"displayOrder")||0);if(!status)errors.push("Trạng thái không hợp lệ.");if(!Number.isInteger(displayOrder)||displayOrder<0)errors.push("Thứ tự phải là số nguyên không âm.");return{status,displayOrder};}
export function parseManagedForm(type:ManagedKind,form:FormData):{data?:ManagedInput;errors:string[]}{const errors:string[]=[];const shared=common(form,errors);if(type==="link"){const kind=LINK_KINDS.find(item=>item===value(form,"kind"));const label=value(form,"label");const rawUrl=value(form,"url");const validUrl=url(rawUrl,true,errors,"URL");if(!kind)errors.push("Loại link không hợp lệ.");if(!label||label.length>120)errors.push("Nhãn phải có 1–120 ký tự.");if(!rawUrl)errors.push("URL là bắt buộc.");if(!shared.status||!kind||!validUrl||errors.length)return{errors};return{errors,data:{kind,label,url:validUrl,openNewTab:form.get("openNewTab")==="on",status:shared.status,displayOrder:shared.displayOrder}};}const question=value(form,"question");const answer=value(form,"answer");if(!question||question.length>240)errors.push("Câu hỏi phải có 1–240 ký tự.");if(!answer||answer.length>5000)errors.push("Câu trả lời phải có 1–5000 ký tự.");if(!shared.status||errors.length)return{errors};return{errors,data:{question,answer,status:shared.status,displayOrder:shared.displayOrder}};}
export function parseSettingForm(form:FormData):{data?:SettingInput;errors:string[]}{const errors:string[]=[];const status=STATUSES.find(item=>item===value(form,"status"));const siteName=value(form,"siteName"),tagline=value(form,"tagline"),footerText=value(form,"footerText"),privacyNote=value(form,"privacyNote"),seoTitle=value(form,"seoTitle"),seoDescription=value(form,"seoDescription");const rawCanonical=value(form,"canonicalUrl"),canonicalUrl=url(rawCanonical,false,errors,"Canonical URL");const seoImagePath=value(form,"seoImagePath")||null;if(!siteName||siteName.length>120)errors.push("Tên site phải có 1–120 ký tự.");if(!tagline||tagline.length>240)errors.push("Tagline phải có 1–240 ký tự.");if(!footerText||footerText.length>500)errors.push("Footer text phải có 1–500 ký tự.");if(!privacyNote||privacyNote.length>5000)errors.push("Privacy note phải có 1–5000 ký tự.");if(!seoTitle||seoTitle.length>70)errors.push("SEO title phải có 1–70 ký tự.");if(!seoDescription||seoDescription.length>180)errors.push("SEO description phải có 1–180 ký tự.");if(seoImagePath&&(!seoImagePath.startsWith("/")||seoImagePath.length>500))errors.push("SEO image path phải là đường dẫn nội bộ tối đa 500 ký tự.");if(!status)errors.push("Trạng thái không hợp lệ.");if(!status||errors.length)return{errors};return{errors,data:{siteName,tagline,footerText,privacyNote,seoTitle,seoDescription,canonicalUrl,seoImagePath,status}};}
